WebShop/Controllers/CompanyController.cs
using DomainLayer.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RepositoryLayer;
using RepositoryLayer.Infrascructure.Company;
using ServiceLayer.Property.CompanyService;
using ServiceLayer.Property.ProductServce;
using System.Data;
using TestOnion.Models;
using WebShop.Models;

namespace WebShop.Controllers
{
    public class CompanyController : Controller
    {
        private readonly ICompanyService _company;
        private readonly IProductService _product;
        private ApplicationContext context;

        public CompanyController(ICompanyService company, IProductService product)
        {
            this._company = company;
            this._product = product;
        }

        [HttpGet]
        //[Authorize(Roles = "admin, moder,user")]
        public IActionResult Index()
        {
            List<CompanyViewModel> model = new List<CompanyViewModel>();
            if (_company != null)
            {
                _company.GetAll().ToList().ForEach(u =>
                {
                    CompanyViewModel company = new CompanyViewModel
                    {
                        Id = u.Id,
                        CompanyIdentity = u.CompanyIdentity,
                        CompanyNamme = u.CompanyNamme,
                    };
                    model.Add(company);
                });
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult AddCompany()
        {
            CompanyViewModel company = new CompanyViewModel();

            return View("AddCompany", company);
        }

        [HttpPost]
        public ActionResult AddCompany(CompanyViewModel company)
        {
            Company company1 = new Company
            {
                CompanyNamme = company.CompanyNamme,
                CompanyIdentity = company.CompanyIdentity,
            };
            _company.Create(company1);
            if (company1.Id > 0)
            {
                return RedirectToAction("index");
            }
            return View(company);
        }

        public ActionResult EditCompany(int? id)
        {
            CompanyViewModel model = new CompanyViewModel();
            if (id.HasValue && id != 0)
            {
                Company company = _company.Get(id.Value);
                model.CompanyIdentity = company.CompanyIdentity;
                model.CompanyNamme = company.CompanyNamme;
            }
            return View("EditCompany", model);
        }

        [HttpPost]
        public ActionResult EditCompany(CompanyViewModel model)
        {
            Company company = _company.Get(model.Id);
            company.CompanyNamme = model.CompanyNamme;
            company.ModifiedDate = DateTime.UtcNow;
            company.CompanyIdentity = model.CompanyIdentity;
            _company.Update(company);
            if (company.Id > 0)
            {
                return RedirectToAction("index");
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult DeleteCompany(int id)
        {
            Company company = _company.Get(id);
            string name = $"{company.CompanyNamme} {company.CompanyIdentity}";
            return View("DeleteCompany", name);
        }

        [HttpPost]
        public ActionResult DeleteCompany(long id)
        {
            _company.Delete(id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult CompanyProfile(int? id)
        {
            CompanyViewModel model = new CompanyViewModel();
            if (id.HasValue && id != 0)
            {
                Company company = _company.Get(id.Value);
                model.CompanyIdentity = company.CompanyIdentity;
                model.CompanyNamme = company.CompanyNamme;
            }
            return View("CompanyProfile", model);
        }
        [HttpPost]
        public ActionResult CompanyProfile(CompanyViewModel model)
        {
            Company company = _company.Get(model.Id);
            company.CompanyIdentity = model.CompanyIdentity;
            company.CompanyNamme = model.CompanyNamme;
            return View(model);
        }
    }
}

WebShop/Controllers/HomeController.cs
using DomainLayer.Models;
using Microsoft.AspNetCore.Mvc;
using RepositoryLayer;
using RepositoryLayer.Infrascructure.Cart;
using ServiceLayer.Property.Category;
using ServiceLayer.Property.ProductServce;
using System.Diagnostics;
using System.Security.Claims;
using WebShop.Models;

namespace WebShop.Controllers
{
    public class HomeController : Controller
    {
        private readonly IProductService _product;
        private readonly ICategoryService _category;
        private ApplicationContext context;
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger, IProductService product, ICategoryService category)
        {
            _logger = logger;
            this._category = category;
            this._product = product;
        }
        [HttpGet]
        public ActionResult OpenCategory(int id)
        {
            List<ProductViewModel> models = new List<ProductViewModel>();
            if(_category != null)
            {
                _category.GetAllProduct(id).ToList().ForEach(u =>
                {
                    ProductViewModel procut = new ProductViewModel
                    {
                        ProductName = u.ProductName,
                        ProductDescription = u.ProductDescription,
                    };
                    models.Add(procut);
                });
            }
            return View("OpenCategory", models);
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Chat()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebShop/Controllers/ProductController.cs
using DomainLayer.Models;
using Microsoft.AspNetCore.Mvc;
using RepositoryLayer;
using ServiceLayer.Property.CompanyService;
using ServiceLayer.Property.ProductServce;
using WebShop.Models;

namespace WebShop.Controllers
{
    public class ProductController : Controller
    {
        private readonly ICompanyService _company;
        private readonly IProductService _product;
        private ApplicationContext context;

        public ProductController(ICompanyService company, IProductService product)
        {
            this._company = company;
            this._product = product;
        }

        [HttpGet]
        public IActionResult Index()
        {
            List<ProductViewModel> model = new List<ProductViewModel>();
            if (_product != null)
            {
                _product.GetAll().ToList().ForEach(u =>
                {
                    Company company = _company.Get(u.CompanyId);
                    ProductViewModel product = new ProductViewModel()
                    {
                        Id = u.Id,
                        ProductName = u.ProductName,
                        ProductNumber = u.ProductNumber,
                        Price = u.Price,
                        ProductDescription = u.ProductDescription,
                        CompanyName = company.CompanyNamme,
                        CategoryId = (int)u.CategoryId
                    };
                    model.Add(product);
                });
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult AddProduct()
        {
            ProductViewModel model = new ProductViewModel();

            return View("AddProduct", model);
        }

        [HttpPost]
        public ActionResult AddProduct(ProductViewModel model)
        {
            Products products = new Products
            {
                ProductName = model.ProductName,
                CompanyId = model.CompanyId,
                Price = model.Price,
                ProductDescription = model.ProductDescription,
                ProductNumber = model.ProductNumber,
                CategoryId = model.CategoryId
            };
            _product.Create(products);
            if (products.Id > 0)
            {
                return RedirectToAction("index");
            }
            return View(products);
        }

        public ActionResult EditProduct(int? id)
        {
            ProductViewModel model = new ProductViewModel();
            if (id.HasValue && id != 0)
            {
                Products products = _product.Get(id.Value);
                model.ProductNumber = products.ProductNumber;
                model.ProductName = products.ProductName;
                model.ProductDescription = products.ProductDescription;
                model.CompanyId = products.CompanyId; 
                model.Price = products.Price;
            }
            return View("EditProduct", model);
        }

        [HttpPost]
        public ActionResult EditProduct(ProductViewModel model)
        {
            Products products = _product.Get(model.Id);
            products.CompanyId = model.CompanyId;
            products.ProductNumber = model.ProductNumber;
            products.ProductDescription = model.ProductDescription;
            products.ProductName = model.ProductName;
            products.Price = model.Price;
            products.ModifiedDate = DateTime.UtcNow;
            _product.Update(products);
            if (products.Id > 0)
            {
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult DeleteProduct(int id)
        {
            Products products = _product.Get(id);
            string name = $"{products.ProductName} {products.ProductNumber}";
            return View("DeleteProduct", name);
        }

        [HttpPost]
        public ActionResult DeleteProduct(long id)
        {
            _product.Delete(id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult ProductProfile(int? id)
        {
            
            ProductViewModel model = new ProductViewModel();

            if (id.HasValue && id != 0)
            {
                Products products = _product.Get(id.Value);
                Company company = _company.Get(products.CompanyId);
                model.ProductNumber = products.ProductNumber;
                model.ProductDescription = products.ProductDescription;
                model.ProductName = products.ProductName;
                model.Price = products.Price;
                model.CompanyName = company.CompanyNamme;
            }
            return View("ProductProfile", model);
        }
        [HttpPost]
        public ActionResult ProductProfile(ProductViewModel model)
        {
            Products products = _product.Get(model.Id);
            Company company = _company.Get(products.CompanyId);
            products.ProductName = model.ProductName;
            products.Price = model.Price;
            products.ProductDescription = model.ProductDescription;
            company.CompanyNamme = model.CompanyName;
            return View(model);
        }
    }
}

WebShop/Views/Home/Chat.cshtml
@*@page
@model WebShop.Views.Home.ChatModel
@{
}

<div class="container">
    <div>
        <label>Your name:</label>
        <input type="text" id="displayname" />
    </div>

<div class="mt-5">
    <input type="text" id="message" />
    <input type="button" id="sendmessage" value="Send" />

</div>
    <div class="mt-3">
        <ul id="discussion"></ul>
    </div>

</div>

<script src="https://cdn.jsdelivr.net/npm/@@microsoft/signalr@7.0.10/dist/browser/signalr.min.js"></script>

<script>
    var connection = new signalR.HubConnectionBuilder().withUrl("/chat").build();
    connection.start().catch(fuction (err) {
        return console.error(err.toString());
    });

    document.getElementById("sendmessage").addEventListener("click", function(event){
        var user = document.getElementById("displayname").value;
        var message = document.getElementById("message").value;

        connection.invoke("SendMessage", user, message).catch(function(err){
            return console.error(err.toString());
        });
        event.preventDefault();
    });
    connection.on("ReceiveMessage", function(user,message){
        var encodedMsg = user + ": " + message;
        var li = document.createElement("li");

        li.textContent = encodedMsg;
        document.getElementById("discussion").appendChild(li);
    });
</script>*@

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Metanit.com</title>
</head>
<body>
    <div>
        Введите логин:<br />
        <input id="userName" type="text" /><br /><br />
        Введите сообщение:<br />
        <input type="text" id="message" /><br /><br />
        <input type="button" id="sendBtn" value="Отправить" disabled="disabled" />
    </div>
    <div id="chatroom"></div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/6.0.1/signalr.js"></script>
    <script>
        const hubConnection = new signalR.HubConnectionBuilder()
            .withUrl("/chat")
            .build();

        document.getElementById("sendBtn").addEventListener("click", function () {
            const userName = document.getElementById("userName").value;   // получаем введенное имя
            const message = document.getElementById("message").value;

            hubConnection.invoke("Send", message, userName) // отправка данных серверу
                .catch(function (err) {
                    return console.error(err.toString());
                });
        });
        // получение данных с сервера
        hubConnection.on("Receive", function (message, userName) {

            // создаем элемент <b> для имени пользователя
            const userNameElem = document.createElement("b");
            userNameElem.textContent = `${userName}: `;

            // создает элемент <p> для сообщения пользователя
            const elem = document.createElement("p");
            elem.appendChild(userNameElem);
            elem.appendChild(document.createTextNode(message));

            // добавляем новый элемент в самое начало
            // для этого сначала получаем первый элемент
            const firstElem = document.getElementById("chatroom").firstChild;
            document.getElementById("chatroom").insertBefore(elem, firstElem);
        });

        hubConnection.start()
            .then(function () {
                document.getElementById("sendBtn").disabled = false;
            })
            .catch(function (err) {
                return console.error(err.toString());
            });
    </script>
</body>
</html>

WebShop/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model WebShop.Views.Home.ChatModel
@{
}

<div class="container">
    <div>
        <label>Your name:</label>
        <input type="text" id="displayname" />
    </div>

<div class="mt-5">
    <input type="text" id="message" />
    <input type="button" id="sendmessage" value="Send" />

</div>
    <div class="mt-3">
        <ul id="discussion"></ul>
    </div>

</div>

<script src="https://cdn.jsdelivr.net/npm/@@microsoft/signalr@7.0.10/dist/browser/signalr.min.js"></script>

<script>
    var connection = new signalR.HubConnectionBuilder().withUrl("/chat").build();
    connection.start().catch(fuction (err) {
        return console.error(err.toString());
    });

    document.getElementById("sendmessage").addEventListener("click", function(event){
        var user = document.getElementById("displayname").value;
        var message = document.getElementById("message").value;

        connection.invoke("SendMessage", user, message).catch(function(err){
            return console.error(err.toString());
        });
        event.preventDefault();
    });
    connection.on("ReceiveMessage", function(user,message){
        var encodedMsg = user + ": " + message;
        var li = document.createElement("li");

        li.textContent = encodedMsg;
        document.getElementById("discussion").appendChild(li);
    });
</script>

WebShop/Views/Home/OpenCategory.cshtml
@model IEnumerable<ProductViewModel>
@using TestOnion.Models


<div class="top-buffer"></div>
<div class="panel panel-primary">
    <div class="panel-heading panel-head">Users</div>
    <div class="panel-body">
        <div class="btn-group">
            @*<a id="createEditUserModal" data-toggle="modal" asp-action="AddUser" data-target="#modal-action-user" class="btn btn-primary">*@
            @Html.ActionLink("Добавить", "AddProduct", "Product")
            <i class="glyphicon glyphicon-plus"></i>  Add Company
            </a>
        </div>
        <div class="top-buffer"></div>
        <table class="table table-bordered table-striped table-condensed">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Identity</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.ProductName)</td>
                        <td>@Html.DisplayFor(modelItem => item.CompanyName)</td>
                        <td>@Html.DisplayFor(modelItem => item.ProductNumber)</td>
                        <td>@Html.DisplayFor(modelItem => item.Price)</td>
                        <td>@Html.DisplayFor(modelItem => item.ProductDescription)</td>
                        <td>
                            <a id="editProductModal" data-toggle="modal" asp-action="EditProduct" asp-route-id="@item.Id" data-target="#modal-action-product"
                               class="btn btn-info">
                                <i class="glyphicon glyphicon-pencil"></i>  Edit
                            </a>
                            <a id="deleteProductModal" data-toggle="modal" asp-action="DeleteProduct" asp-route-id="@item.Id" data-target="#modal-action-product" class="btn btn-danger">
                                <i class="glyphicon glyphicon-trash"></i>  Delete
                            </a>
                            <a id="deleteProductModal" data-toggle="modal" asp-action="ProductProfile" asp-route-id="@item.Id" data-target="#modal-action-product" class="btn btn-light">
                                <i class="glyphicon glyphicon-trash"></i>  View
                            </a>
                            <a id="AddToCartProductModal" data-toggle="modal" asp-action="AddToCart" asp-controller="Cart" asp-route-id="@item.Id" data-target="#modal-action-add-to-cart-product" class="btn btn-light">
                                <i class="glyphicon glyphicon-trash"></i>  AddToCart
                            </a>
                        </td>
                    </tr>
                }
                @Html.ActionLink("Компаний", "Index", "Company")
            </tbody>
        </table>
    </div>
</div>