WebShop/Models/UserViewModel.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace TestOnion.Models
{
    public class UserViewModel
    {
        [HiddenInput]
        public Int64 Id { get; set; }
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        [Display(Name = "User Name")]
        public string UserName { get; set; }
        public string Email { get; set; }
        public long RoleId { get; set; }
        public string Password { get; set; }
        [Display(Name = "Added Date")]
        public DateTime AddedDate { get; set; }
    }
}

WebShop/Controllers/CompanyController.cs
using DomainLayer.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RepositoryLayer;
using RepositoryLayer.Infrascructure.Company;
using ServiceLayer.Property.CompanyService;
using ServiceLayer.Property.ProductServce;
using System.Data;
using TestOnion.Models;
using WebShop.Models;

namespace WebShop.Controllers
{
    public class CompanyController : Controller
    {
        private readonly ICompanyService _company;
        private readonly IProductService _product;
        private ApplicationContext context;

        public CompanyController(ICompanyService company, IProductService product)
        {
            this._company = company;
            this._product = product;
        }

        [HttpGet]
        //[Authorize(Roles = "admin, moder,user")]
        public IActionResult Index()
        {
            List<CompanyViewModel> model = new List<CompanyViewModel>();
            if (_company != null)
            {
                _company.GetAll().ToList().ForEach(u =>
                {
                    CompanyViewModel company = new CompanyViewModel
                    {
                        Id = u.Id,
                        CompanyIdentity = u.CompanyIdentity,
                        CompanyNamme = u.CompanyNamme,
                    };
                    model.Add(company);
                });
            }

            return View(model);
        }

        [HttpGet]
        public ActionResult AddCompany()
        {
            CompanyViewModel company = new CompanyViewModel();

            return View("AddCompany", company);
        }

        [HttpPost]
        public ActionResult AddCompany(CompanyViewModel company)
        {
            Company company1 = new Company
            {
                CompanyNamme = company.CompanyNamme,
                CompanyIdentity = company.CompanyIdentity,
            };
            _company.Create(company1);
            if (company1.Id > 0)
            {
                return RedirectToAction("index");
            }
            return View(company);
        }

        public ActionResult EditCompany(int? id)
        {
            CompanyViewModel model = new CompanyViewModel();
            if (id.HasValue && id != 0)
            {
                Company company = _company.Get(id.Value);
                model.CompanyIdentity = company.CompanyIdentity;
                model.CompanyNamme = company.CompanyNamme;
            }
            return View("EditCompany", model);
        }

        [HttpPost]
        public ActionResult EditCompany(CompanyViewModel model)
        {
            Company company = _company.Get(model.Id);
            company.CompanyNamme = model.CompanyNamme;
            company.ModifiedDate = DateTime.UtcNow;
            company.CompanyIdentity = model.CompanyIdentity;
            _company.Update(company);
            if (company.Id > 0)
            {
                return RedirectToAction("index");
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult DeleteCompany(int id)
        {
            Company company = _company.Get(id);
            string name = $"{company.CompanyNamme} {company.CompanyIdentity}";
            return View("DeleteCompany", name);
        }

        [HttpPost]
        public ActionResult DeleteCompany(long id)
        {
            _company.Delete(id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult CompanyProfile(int? id)
        {
            CompanyViewModel model = new CompanyViewModel();
            if (id.HasValue && id != 0)
            {
                Company company = _company.Get(id.Value);
                model.CompanyIdentity = company.CompanyIdentity;
                model.CompanyNamme = company.CompanyNamme;
            }
            return View("CompanyProfile", model);
        }
        [HttpPost]
        public ActionResult CompanyProfile(CompanyViewModel model)
        {
            Company company = _company.Get(model.Id);
            company.CompanyIdentity = model.CompanyIdentity;
            company.CompanyNamme = model.CompanyNamme;
            return View(model);
        }
    }
}

WebShop/Controllers/UserController.cs
using DomainLayer.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RepositoryLayer;
using ServiceLayer.Property.Category;
using ServiceLayer.Property.UserProfileService;
using ServiceLayer.Property.UserService;
using System.Data;
using TestOnion.Models;
using WebShop.Models;

namespace WebShop.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService userService;
        private readonly IUserProfileService userProfileService;
        private readonly ICategoryService categoryService;
        private ApplicationContext context;

        public UserController(IUserService userService, IUserProfileService userProfileService, ICategoryService category)
        {
            this.userService = userService;
            this.userProfileService = userProfileService;
            this.categoryService = category;
        }

        [HttpGet]
        [Authorize(Roles = "Admin, Moder,User")]
        public async Task<IActionResult> Index()
        {
            List<UserViewModel> model = new List<UserViewModel>();
            if (userProfileService != null)
            {
                userService.GetUsers().ToList().ForEach(u =>
                {
                    UserProfile userProfile = userProfileService.GetUserProfile(u.Id);
                    UserViewModel user = new UserViewModel
                    {
                        Id = u.Id,
                        Name = $"{userProfile.FirstName} {userProfile.LastName}",
                        Email = u.Email,
                        Address = userProfile.Address
                    };
                    model.Add(user);
                });
            }
            List<CategoryViewModel> categories = new List<CategoryViewModel>();
            if (categoryService != null)
            {
                categoryService.GetAll().ToList().ForEach(f =>
                {
                    Category category = categoryService.Get(f.Id);
                    CategoryViewModel viewModel = new CategoryViewModel
                    {
                        Id = f.Id,
                        CategoryName = f.CategoryName
                    };
                    categories.Add(viewModel);
                });
            }
            //ViewData["categories"] = categories;
            MultiViewModel multi = new MultiViewModel();
            multi.UserViewModels = model;
            multi.CategoryViewModels = categories;
            //var tuple = new Tuple<List<UserViewModel>, List<CategoryViewModel>>((List<UserViewModel>)userService.GetUsers(), (List<CategoryViewModel>)categoryService.GetAll());
            return View(multi);
        }

        [HttpGet]
        public ActionResult AddUser()
        {
            UserViewModel model = new UserViewModel();
            SelectList roles = new SelectList(context.Role, "Id", "Name");
            ViewBag.Roles = roles;

            return View("AddUser", model);
        }

        [HttpPost]
        public ActionResult AddUser(UserViewModel model)
        {
            User userEntity = new User
            {
                UserName = model.UserName,
                Email = model.Email,
                Password = model.Password,
                AddedDate = DateTime.UtcNow,
                ModifiedDate = DateTime.UtcNow,
                RoleId = model.RoleId,
                //IPAddress = Request.HttpContext.Connection.RemoteIpAddress.ToString(),
                UserProfile = new UserProfile
                {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Address = model.Address,
                    AddedDate = DateTime.UtcNow,
                    ModifiedDate = DateTime.UtcNow,
                    //RoleId = model.RoleId,
                    //IPAddress = Request.HttpContext.Connection.RemoteIpAddress.ToString()
                }
            };
            userService.CreateUser(userEntity);
            if (userEntity.Id > 0)
            {
                return RedirectToAction("index");
            }
            return View(model);
        }

        public ActionResult EditUser(int? id)
        {
            UserViewModel model = new UserViewModel();
            if (id.HasValue && id != 0)
            {
                User userEntity = userService.GetUser(id.Value);
                UserProfile userProfileEntity = userProfileService.GetUserProfile(id.Value);
                model.FirstName = userProfileEntity.FirstName;
                model.LastName = userProfileEntity.LastName;
                model.Address = userProfileEntity.Address;
                model.Email = userEntity.Email;
            }
            return View("EditUser", model);
        }

        [HttpPost]
        public ActionResult EditUser(UserViewModel model)
        {
            User userEntity = userService.GetUser(model.Id);
            userEntity.Email = model.Email;
            userEntity.ModifiedDate = DateTime.UtcNow;
           // userEntity.IPAddress = Request.HttpContext.Connection.RemoteIpAddress.ToString();
            UserProfile userProfileEntity = userProfileService.GetUserProfile(model.Id);
            userProfileEntity.FirstName = model.FirstName;
            userProfileEntity.LastName = model.LastName;
            userProfileEntity.Address = model.Address;
            userProfileEntity.ModifiedDate = DateTime.UtcNow;
            //userProfileEntity.IPAddress = Request.HttpContext.Connection.RemoteIpAddress.ToString();
            userEntity.UserProfile = userProfileEntity;
            userService.UpdateUser(userEntity);
            if (userEntity.Id > 0)
            {
                return RedirectToAction("index");
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult DeleteUser(int id)
        {
            UserProfile userProfile = userProfileService.GetUserProfile(id);
            string name = $"{userProfile.FirstName} {userProfile.LastName}";
            return View("DeleteUser", name);
        }

        [HttpPost]
        public ActionResult DeleteUser(long id)
        {
            userService.DeleteUser(id);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult UserProfile(int? id)
        {
            UserViewModel model = new UserViewModel();
            if (id.HasValue && id != 0)
            {
                User userEntity = userService.GetUser(id.Value);
                UserProfile userProfileEntity = userProfileService.GetUserProfile(id.Value);
                model.FirstName = userProfileEntity.FirstName;
                model.LastName = userProfileEntity.LastName;
                model.Address = userProfileEntity.Address;
                model.Email = userEntity.Email;
            }
            return View("UserProfile", model);
        }
        [HttpPost]
        public ActionResult UserProfile(UserViewModel model)
        {
            User userEntity = userService.GetUser(model.Id);
            userEntity.Email = model.Email;
            userEntity.ModifiedDate = DateTime.UtcNow;
            // userEntity.IPAddress = Request.HttpContext.Connection.RemoteIpAddress.ToString();
            UserProfile userProfileEntity = userProfileService.GetUserProfile(model.Id);
            userProfileEntity.FirstName = model.FirstName;
            userProfileEntity.LastName = model.LastName;
            userProfileEntity.Address = model.Address;
            userProfileEntity.ModifiedDate = DateTime.UtcNow;
            //userProfileEntity.IPAddress = Request.HttpContext.Connection.RemoteIpAddress.ToString();
            userEntity.UserProfile = userProfileEntity;
            return View(model);
        }

    }
}

WebShop/Views/User/AddUser.cshtml
@model UserViewModel
@using TestOnion.Models

<form asp-action="AddUser" role="form">
    <div class="modal-body form-horizontal">
        <div class="row">
            <div class="col-lg-6">
                <div class="form-group">
                    <label asp-for="FirstName" class="col-lg-3 col-sm-3 control-label"></label>
                    <div class="col-lg-6">
                        <input asp-for="FirstName" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="LastName" class="col-lg-3 col-sm-3 control-label"></label>
                    <div class="col-lg-6">
                        <input asp-for="LastName" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="col-lg-3 col-sm-3 control-label"></label>
                    <div class="col-lg-6">
                        <input asp-for="Email" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group">
                    <label asp-for="UserName" class="col-lg-3 col-sm-3 control-label"></label>
                    <div class="col-lg-6">
                        <input asp-for="UserName" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Password" class="col-lg-3 col-sm-3 control-label"></label>
                    <div class="col-lg-6">
                        <input type="password" asp-for="Password" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Address" class="col-lg-3 col-sm-3 control-label"></label>
                    <div class="col-lg-6">
                        <input asp-for="Address" class="form-control" />
                    </div>
                </div>
               @* <div class="form-group">
                    <label asp-for="RoleId" class="col-lg-3 col-sm-3 control-label"></label>
                    <div class="col-lg-6">
                        <input asp-for="RoleId" class="form-control" />
                    </div>
                </div>*@
                @Html.DropDownListFor(model => model.RoleId, ViewBag.Roles as SelectList)
                <input type="submit" value="Создать" class="btn btn-outline-dark" />
            </div>
        </div>
    </div>
</form>

WebShop/Views/User/DeleteUser.cshtml
@model string
@using TestOnion.Models


<form asp-action="DeleteUser" role="form">
    

    <div class="modal-body form-horizontal">
        Are you want to delete @Model?
    </div>
    <input type="submit" value="Удалить" class="btn btn-outline-dark" />
</form>

WebShop/Views/User/EditUser.cshtml
@model UserViewModel
@using TestOnion.Models

<form asp-action="EditUser" role="form">
   
    <div class="modal-body form-horizontal">
        <div class="row">
            <input asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="FirstName" class="form-control" />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="LastName" class="form-control" />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="Email" class="form-control" />
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Address" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="Address" class="form-control" />
                </div>
            </div>
            <input type="submit" value="Создать" class="btn btn-outline-dark" />
        </div>
    </div>
</form>

WebShop/Views/User/Index.cshtml
@model MultiViewModel
@using TestOnion.Models


<div class="top-buffer"></div>
<div class="panel panel-primary">
    <div class="panel-heading panel-head">Users</div>
    <div class="panel-body">
        <div class="btn-group">
                @Html.ActionLink("Добавить", "AddUser", "User")
                <i class="glyphicon glyphicon-plus"></i>  Add User
            </a>
        </div>
        <div class="top-buffer"></div>
        <table class="table table-bordered table-striped table-condensed">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Address</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.UserViewModels)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.Name)</td>
                        <td>@Html.DisplayFor(modelItem => item.Email)</td>
                        <td>@Html.DisplayFor(modelItem => item.Address)</td>
                        <td>
                            <a id="editUserModal" data-toggle="modal" asp-action="EditUser" asp-route-id="@item.Id" data-target="#modal-action-user"
                               class="btn btn-info">
                                <i class="glyphicon glyphicon-pencil"></i>  Edit
                            </a>
                            <a id="deleteUserModal" data-toggle="modal" asp-action="DeleteUser" asp-route-id="@item.Id" data-target="#modal-action-user" class="btn btn-danger">
                                <i class="glyphicon glyphicon-trash"></i>  Delete
                            </a>
                            <a id="deleteUserModal" data-toggle="modal" asp-action="UserProfile" asp-route-id="@item.Id" data-target="#modal-action-user" class="btn btn-light">
                                <i class="glyphicon glyphicon-trash"></i>  View
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        Table Categories
        <table class="table table-bordered table-striped table-condensed">
            <thead>
                <tr>
                    <th>Name</th>
                </tr>
            </thead>
            <tbody>

            <tbody>
                @foreach (var item in Model.CategoryViewModels)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.CategoryName)</td>
                        <td>
                            <a id="editUserModal" data-toggle="modal" asp-action="OpenCategory" asp-controller="Home" asp-route-id="@item.Id" data-target="#modal-action-user"
                               class="btn btn-info">
                                <i class="glyphicon glyphicon-pencil"></i>  View
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <a asp-action="Index" asp-controller="Company" class="btn btn1" style="width:300px">Компаний</a>
        <a asp-action="Chat" asp-controller="Home" class="btn btn1" style="width:300px">Чат</a>
    </div>
</div>

WebShop/Views/User/UserProfile.cshtml
@model UserViewModel
@using TestOnion.Models

<form asp-action="UserProfile" role="form">

    <div class="modal-body form-horizontal">
        <div class="row">
            <input asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="FirstName" class="form-control" readonly/>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="LastName" class="form-control"  readonly/>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="Email" class="form-control" readonly/>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Address" class="col-lg-3 col-sm-3 control-label"></label>
                <div class="col-lg-6">
                    <input asp-for="Address" class="form-control" readonly/>
                </div>
            </div>
        </div>
    </div>
</form>